// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/book/book.proto

package book

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Year                 uint32   `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Size                 uint32   `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Rate                 float64  `protobuf:"fixed64,6,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_74ca522ab1843f57, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Book) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Book) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func init() {
	proto.RegisterType((*Book)(nil), "book.Book")
}

func init() {
	proto.RegisterFile("api/book/book.proto", fileDescriptor_74ca522ab1843f57)
}

var fileDescriptor_74ca522ab1843f57 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8f, 0x31, 0xab, 0x83, 0x30,
	0x14, 0x85, 0x89, 0x2f, 0x0a, 0x2f, 0xf0, 0xde, 0x90, 0xf7, 0x28, 0x19, 0xa5, 0x93, 0x93, 0x91,
	0xb6, 0x4b, 0xe9, 0xe6, 0x4f, 0x70, 0xec, 0x52, 0x62, 0x0d, 0xe6, 0x12, 0xe5, 0x4a, 0x8c, 0x94,
	0x3a, 0xf5, 0xa7, 0x97, 0xc4, 0x2e, 0x87, 0xef, 0x7c, 0x70, 0xe1, 0x1e, 0xf6, 0xa7, 0x26, 0x90,
	0x2d, 0xa2, 0x8d, 0x51, 0x4e, 0x0e, 0x3d, 0x72, 0x1a, 0x78, 0xff, 0x22, 0x8c, 0xd6, 0x88, 0x96,
	0xff, 0xb2, 0x04, 0x3a, 0x41, 0x72, 0x52, 0xfc, 0x34, 0x09, 0x74, 0xfc, 0x9f, 0xa5, 0x1e, 0xfc,
	0xa0, 0x45, 0x92, 0x93, 0xe2, 0xbb, 0xd9, 0x0a, 0xdf, 0xb1, 0x4c, 0x2d, 0xde, 0xa0, 0x13, 0x5f,
	0x51, 0x7f, 0x1a, 0xe7, 0x8c, 0x3e, 0xb5, 0x72, 0x82, 0xc6, 0xfb, 0xc8, 0xc1, 0xcd, 0xb0, 0x6a,
	0x91, 0x6e, 0x2e, 0x70, 0x70, 0x4e, 0x79, 0x2d, 0xb2, 0x9c, 0x14, 0xa4, 0x89, 0x5c, 0x1f, 0xae,
	0x55, 0x0f, 0xde, 0x2c, 0x6d, 0x79, 0xc7, 0x51, 0x8e, 0xca, 0x9d, 0xb4, 0xb1, 0x95, 0x34, 0x8f,
	0xea, 0x7c, 0x9b, 0xb5, 0x03, 0x35, 0xc0, 0xaa, 0xe5, 0x64, 0xfb, 0xf8, 0xfd, 0x25, 0x44, 0x9b,
	0xc5, 0x0d, 0xc7, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0x8d, 0xf7, 0x36, 0xda, 0x00, 0x00,
	0x00,
}
